### ISSUE TITLE
position: fixed for IE11

### ISSUE THREAD

**Issue by paull39** [postcss/autoprefixer#1004]
Hey,
according to https://www.w3.org/TR/css-position-3/#fixed-pos
position fixed should not scroll along with your interaction

but in IE11 it does. My working solution is -ms-page as a replacement.

Thank you for your good work 👍

**Comment by ai** [comment]
Hi. You should create a custom plugin to cover this case.

Autoprefixer is about prefixes, not polyfills and bugs fixes. According [Can I Use](https://caniuse.com/#search=fixed) IE supports `position: fixed`. So using `-ms-page` is a hack to avoid a bug, not prefix.

Technically, I can’t even add `-ms-page` because Autoprefixer is based on Can I Use data and Can I Use says that everything is OK.
