### ISSUE TITLE
how to disable IE and Edge browsers from autoprefixing ?

### ISSUE THREAD

**Issue by riiccardo** [postcss/autoprefixer#1103]
In browserslist doc said:

> You can add `not` to any query.

`browsers: ['not ie', 'not ie_mob', '> 1%', 'last 2 version']`

how to ignore ie all versions ?

im using browser navigator 
if browser is IE show `your_browser_is_outdate.html`

i dont want to add `-ms` prefix to my css file 

Regards

**Comment by ai** [comment]
@riiccardo do not use `browsers` option. As we said in the docs:

> The best practice is to use .browserslistrc config or browserslist key in package.json to share target browsers with Babel, ESLint and Stylelint.

**Comment by ai** [comment]
1. Create `.browserslist` config file
2. Write there:

```
defaults
not ie > 0
not ie_mob > 0
not dead
```

**Comment by riiccardo** [comment]
thanks :)

**Comment by riiccardo** [comment]
best config for prefixing ? cover modern browsers for lightweight css file

**Comment by ai** [comment]
What is your use case? Why do you think your users will use only modern browsers?

**Comment by Dan503** [comment]
The simple answer to your question assuming you don't want to reconfigure your entire build process is to remove `'last 2 version'` from the list.

Since it is last I think it is overriding any previous commands and `'last 2 version'` includes the last 2 versions of IE (IE 10 and 11).

**Comment by riiccardo** [comment]
my mean what is best config for `.browserslist` forget modern browser

**Comment by Dan503** [comment]
This is all you need `browsers: ['> 1%']` Only browsers with greater than 1% global marketshare will be prefixed. You can increase the percentage to cut out even more browsers if you really want.

**Comment by Dan503** [comment]
oh but if you want to not include IE at all then you will need `browsers: ['> 1%', 'not ie']`

(IE still has a pretty large market share)

**Comment by Dan503** [comment]
So yeah actually, what you had was almost fine. You just needed to remove the `'last 2 version'` part off the end.

**Comment by ai** [comment]
@Dan503 do not use `browsers` option.

And `not IE` doesn't work (for a purpose).

Correct query will be:

```
# .browserslistrc
> 1%
not ie > 0
not ie_mob > 0
```

But all thinking “I don't care about non popular browsers” is very bad for community. @riiccardo is from Iran. I am from Russia. At least I suffer a lot because of Western developers didn't support Opera, since it was not popular in the world (by very popular in Russia). Looking only for popular browsers killing innovations in browsers and moving us to “IE6 hell” again (should I remind that developers at that time supported only IE6 because all other browsers was not popular).

This is why we keep `last 2 versions` in `defaults`.
