### ISSUE TITLE
Missing polyfill for break-* 

### ISSUE THREAD

**Issue by BlitZz96** [postcss/autoprefixer#1119]
When writing `page-break-after: always` for example, the css gets compiled to `break-after: page` which does not work in the [majority of the browsers](https://caniuse.com/#feat=css-page-break).

Is this intentional?

**Comment by ai** [comment]
You need to write `break-after: auto;`.

Then it will be compiled to https://github.com/postcss/autoprefixer/blob/master/test/cases/multicolumn.out.css

**Comment by ai** [comment]
If you want to write `page-break-after: always` give me what CSS output do you expect

**Comment by BlitZz96** [comment]
My goal was to make a print document break after each table. I wrote `.print-break { page-break-after: always }`. As specified above, the css got rewritten to `break-after: page` and this did not break the page as expected. My workaround now is to add this class outside my webpack environment.

I would expect css to output `page-break-after: always` or:

```CSS
.print-break {
  break-after: page;
  page-break-after: always;
}
```

I do not know too much about this, sadly.

**Comment by ai** [comment]
Sorry, it is not prefixes and Autoprefixer doesn’t try to make polyfills.

This is why I will keep the current behavior (for compatibility) but will not improve it.

You can write a custom PostCSS plugin for this work.

**Comment by Dan503** [comment]
@ai it sounds like it isn't a case of a feature request. It sounds like Autoprefixer is doing something it maybe isn't supposed to.

@BlitZz96 Try out the new playground Autoprefixer has.

1. Check out the Autoprefixer repo
2. `npm i`
3. Install gulp-cli if you don't have it already `npm i gulp-cli -g`
4. Run `gulp play`
5. Write the CSS you have written in your project into the `playground/input.css` file
6. Look at the output in `playground/input.css`, is it what you expect?
7. If not, copy/paste the CSS you wrote in `input.css` into a code block in this issue exactly as written and mark it as "input CSS"
8. copy/paste the CSS in `output.css` into a code block in this issue exactly as written and mark it as "output CSS"
9. copy/paste the CSS in `output.css` into another code block but this time make adjustments to it so that it displays what you expect it to output instead. Mark that code block as "expected output CSS"

We will have a much clearer understanding of what the issue is if you provide those three code samples.

PS. This makes me realise how badly Autoprefixer needs a real official website with a basic converter available for users to use.

**Comment by BlitZz96** [comment]
I really appreciate the feedback, guys!

I tried the page 
> go to http://autoprefixer.github.io/ and do the experiment there.

And it does indeed not insert nor delete anything. I suppose I have to go deeper in my vue project to see what might cause this issue. I thought autoprefixer was the only css "fixing" plugin I used.

Really good debug solutions @Dan503! I am sorry this issue was a false.
