### ISSUE TITLE
Warnings not pointing to original files in source map

### ISSUE THREAD

**Issue by Ustice** [postcss/autoprefixer#1171]
I have a `LESS -> autoprefixer` pipeline, and it's working; however the warnings that are shown are not pointing to the original file, but instead to the generated CSS. 

Here is my current pipeline, but I have also gone through several other configurations, including using `gulp-postcss`, and using autoprefixer though the `less-plugin-autoprefix` LESS plugin. 

```javascript
const gulp = require('gulp');
const util = require('gulp-util');
const less = require('gulp-less');
const sourcemaps = require('gulp-sourcemaps');
const autoprefixer = require('gulp-autoprefixer');

gulp.task('less', ['clear:stylesheets'], () => {
  return gulp.src(['styles/*.less'])
    .pipe(sourcemaps.init())
    .pipe(less({
      paths: ['styles'],
    }))
    .pipe(autoprefixer({
      grid: 'autoplace',
      cascade: true,
      browsers: require('./package.json').browserslist,
    }))
    .on("error", handleErrors)
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('public/stylesheets'))
});

function handleErrors (err) {
  util.log(util.colors.red("[Error]"), err);
  this.emit('end');
}
```

Here is the warning that I am getting. (I only altered the path of the project root.) Notice that it is referring to nonexistent css file. 
```
[13:01:35] gulp-autoprefixer:
  autoprefixer: /project-root/styles/modals.css:261:3: IE does not support align-items on grid containers. Try using align-self on child elements instead: .metric-modal .modal-body > * { align-self: center }
  autoprefixer: /project-root/styles/modals.css:298:3: Autoplacement does not work without grid-template-rows property
```

**Comment by ai** [comment]
He. Unfortunately, most of this issue happens because of LESS and PostCSS uses different blocks in CSS in the source map mappings. This is why these issues are not number 1 priority for me.

What solutions do I see:

1. Use any PostCSS based preprocessor. It will increase performance and simplify build pipeline.
2. Debug the issue by yourself and send PR to PostCSS. Here is a useful tool to investigate any source map issues https://sokra.github.io/source-map-visualization/

I am closing this issue, since it is more related to PostCSS than to Autoprefixer
