### ISSUE TITLE
caniuse-lite 1.0.30000975 is broken

### ISSUE THREAD

**Issue by ZachTRice** [postcss/autoprefixer#1224]
Installing autoprefixer installs the latest `caniuse-lite` package which is v1.0.30000975. This version is currently broken, see: https://github.com/ben-eb/caniuse-lite/issues/27

Once the latest caniuse-lite fix has been published, I would update the package.json to:
`"caniuse-lite": "^1.0.30000976",` (or any version later than v1.0.30000975 )

In the meantime, it might be worth changing to `"caniuse-lite": "1.0.30000974",`

**Comment by ai** [comment]
1. `caniuse-lite` will not be fixed. It is just repack of `caniuse-db`. `caniuse-db` community doesn't solve their issues, since this db is uploaded to npm as-is.
2. Locking version will not fix the problem here. Anyway `postcss-preset-env` will use new version and will throw the error.
3. Browserslist already released a dirty hack to fix the error. Just update Browserslist and subscribe to https://twitter.com/browserslist (we described the whole situation there).
