### ISSUE TITLE
autoprefixer ignores webpack stats

### ISSUE THREAD

**Issue by jonnylink** [postcss/autoprefixer#1225]
Using either `stats: {warnings: false}` or `warningsFilter` has no effect on warnings. I seen a few past issues where people want to, for example, not have a console filled with warnings about linear-gradients. 

While I understand this isn't great, we can't force the 3rd parties to update their css. It isn't helpful, it's noise, and users should be trusted to make that distinction.

I'm admittedly a bit new to webpack, so it's possible I've made a mistake. If that's the case, then I humbly apologize. Regardless, thanks for your time and energy to make things that other people find useful (even if I'm griping about this).

**Comment by ai** [comment]
You need to open an issue in `postcss-loader`. Autoprefixer uses standard PostCSS API to show warnings. The PostCSS runner should filter warnings according to environment API.

But Autoprefixer warnings tell about big issues in input CSS. They all should be fixed, because they could create a problem in the future or tells about unnecessary CSS rules (because they just doesn’t work).

**Comment by jonnylink** [comment]
Thank you. I'll file there. 

I understand they might not work, but like I said, I can't fix 3rd packages (I can make a PR, and did, but that doesn't mean it gets fixed). The css in question never even makes it onto the page, so for all those reasons the warning isn't useful and it makes it so that serious warnings are much harder to see. The good intentions in this case can actually lead to bad outcomes.

**Comment by ai** [comment]
You can add another PostCSS plugin after Autoprefixer which will clean warnings:

```js
module.exports = postcss.plugin('warn-cleaner', () => {
  return (root, result) => {
    result.warnings = []
  }
})
```
