### ISSUE TITLE
Why should I not enable 'grid' If I use 'display: contents;'?

### ISSUE THREAD

**Issue by weineel** [postcss/autoprefixer#1258]
https://github.com/postcss/autoprefixer/blob/b07ba02357839037ecbf29d48bef04b594e3016f/lib/processor.js#L165-L170

**Comment by ai** [comment]
cc @Dan503

**Comment by Dan503** [comment]
Maybe the warning is a bit too broad. It is intended to stop people from using `display: grid` on the parent and `display: contents` on a child element. This combination is impossible for us to replicate in Autoprefixer since IE doesn't support `display: contents` and it will make the grid appear differently in IE.

It is difficult for us to tell if the element that has `display: contents` is a part of the grid element or not. We could possibly restrict the warning so that it only appears if we know for sure that it is being used on a grid cell using grid area code or matching selectors. That's difficult to do though.

The thinking with this simple version of the warning is that if authors are using Autoprefixer for CSS Grid translations then they are probably aiming to make IE have the same layout as modern browsers. Since IE doesn't support `display: contents` we are basically warning the user that the layout will appear differently in IE.

The warnings are there to assist users so that they are able to create consistent layouts across IE and modern browsers. We use the warning to say "Hey! IE is going to look different if you do that. Are you sure about this?"

**Comment by Dan503** [comment]
If you understand the ramifications in IE and you are intentionally using `display: contents` on purpose, I recommend using an "ignore next" control comment on the `display: contents` rule.

```css
.element {
  /* autoprefixer: ignore next */
  display: contents;
}
```

**Comment by Dan503** [comment]
Also, it is not safe to be using `display: contents` right now anyway. Almost every browser still features a critical bug that hides the element from the accessibility tree, so unless you are using `display: contents` on a `<div>` element, you shouldn't be using `display: contents at all right now. Not until the bug is fixed across all major browsers anyway.

https://caniuse.com/#feat=css-display-contents

**Comment by weineel** [comment]
I see, thanks.
