### ISSUE TITLE
Input Error: You must pass a valid list of files to parse

### ISSUE THREAD

**Issue by yonghengBao** [postcss/autoprefixer#1314]
项目目录没有中文和空格也报You must pass a valid list of files to parse
node版本是10.18.0
npm 版本是6.13.4
autoprefixer 版本9.7.6

**Comment by ai** [comment]
Hi. Sorry, I do not know Chinese. You can try to ask in your local community.

It seems like, you send wrong arguments to `postcss-cli`. Here is guide: https://github.com/postcss/postcss-cli#readme

I am closing this issue because this is is `postcss-cli` DX issue, not Autoprefixer.

---



你好。对不起，我不懂中文。你可以试着去当地社区问问。

似乎，您向“postcss cli”发送了错误的参数。以下是指南：https://github.com/postcss/postcss cli#自述

我关闭此问题是因为这是'postss cli'DX问题，而不是Autoprefixer问题。
