### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by 1vanguard** [postcss/autoprefixer#1341]
It not works at all. I installed and reinstalled it several times but nothing helps (((
There are no changes in code after run the command named Autoprefixer: Run.
Hmmm .. But 2.2.0 version with "Autoprefix CSS" works well.
What's wrong?

**Comment by 1vanguard** [comment]
Hmmm .. But 2.2.0 version works well.
What's wrong?

**Comment by Dan503** [comment]
You will need to give more details.

How exactly are you using Autoprefixer?
Can you show a code sample?
What version of node are you using?
What errors are you getting?
What version of what compiler are you using?
What version of PostCSS are you using?

Chances are the issue is in your specific configuration rather than an issue with Autoprefixer itself.

**Comment by Johnny99211** [comment]
Also not working for me but I've added some details for you. Hope we can find a fast solution. Somehow it's not working.

**Comment by k-nacion** [comment]
Autoprefixer version 10+ is not working well with gulp-postcss. It says that it is not a postcss plugin. it work well when I tried to autoprefixer version 9.6.0

**Comment by ai** [comment]
@k-nacion update `gulp-postcss` to 9.x
