### ISSUE TITLE
Support print-color-adjust

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#1454]
Spec: https://www.w3.org/TR/css-color-adjust-1/#print-color-adjust
Caniuse: https://caniuse.com/mdn-css_properties_print-color-adjust

> The [color-adjust](https://www.w3.org/TR/css-color-adjust-1/#propdef-color-adjust) shorthand allows an author to set all of the performance-motivated color adjustment properties in one declaration. (Currently, there is only one such property—[print-color-adjust](https://www.w3.org/TR/css-color-adjust-1/#propdef-print-color-adjust)—but more might be added in the future.)

> The [color-adjust](https://www.w3.org/TR/css-color-adjust-1/#propdef-color-adjust) shorthand is currently deprecated. Authors should use the more specific [print-color-adjust](https://www.w3.org/TR/css-color-adjust-1/#propdef-print-color-adjust) property, to avoid accidentally resetting performance-based color adjustments in other contexts than the one intended.

**Comment by lukewarlow** [comment]
Imo that doesn't feel like something that's the job of autoprefixer. Trying to second guess the behaviour developers want sounds like the job of a specific postcss plugin rather than this tool.

**Comment by ai** [comment]
I think @yisibl asks to add `-webkit-print-color-adjust` for `print-color-adjust`. Am I right?

**Comment by yisibl** [comment]
> I think @yisibl asks to add `-webkit-print-color-adjust` for `print-color-adjust`.

Yes!

**Comment by ai** [comment]
`print-color-adjust` was added to `caniuse-lite` https://github.com/browserslist/caniuse-lite/commit/7228ee1cc76fb0f6c82c303dd781a4e80bb407b8

Now we need to wait `caniuse-db` to trigger new release of `caniuse-lite`. Then we will be able to use it in Autoprefixer.

**Comment by ai** [comment]
Fixed 51b991c

- [x] `print-color-adjust` now generates `-webkit-print-color-adjust`
- [x] Old `color-adjust` works too, but generates a warning

**Comment by ai** [comment]
The fix was released in 10.4.6

**Comment by thecrypticace** [comment]
@ai This update causes autoprefixer to generate `-moz-print-color-adjust` for old versions of FF — however this property does not exist. It should instead output `color-adjust` for old versions of FF which didn't add support for print-color-adjust until FF 97 which was released in early February this year.

I verified that `-moz-print-color-adjust` is indeed not a valid property name in newer and older versions of FF:

<img width="345" alt="Screen Shot 2022-05-02 at 09 22 37" src="https://user-images.githubusercontent.com/614993/166241007-b5f11c8d-08af-4f5a-add3-ed5a49f92bee.png">

**Comment by ai** [comment]
Adding `color-adjust` could later trigger Autoprefixer to print a warning? Can we ignore Firefox property?

**Comment by ai** [comment]
FF ESR needs `color-adjust`, we need to support it.

**Comment by ai** [comment]
Fixed 8fe5b66

**Comment by Martinspire** [comment]
Why is the warning there for `color-adjust` to force `print-color-adjust`? Most implementations I've seen are still using `color-adjust` so many projects are now getting messages about being deprecated. But because its an external dependency, you don't really want to fix that yourself. But it does show up in a lot of pipelines.

For example, my Angular project now shows me 5 messages about this property in 2 different dependencies. And since I can't override autoprefixer settings, there is now a big pile of text in my browser console before I get to my own project.

I get that you want people to use the new property, but I don't think its time to already show deprecation messages on the `color-adjust` since that will remain working for a while.

**Comment by ai** [comment]
> Why is the warning there for color-adjust to force print-color-adjust?

Because `color-adjust` was deprecated.

> For example, my Angular project now shows me 5 messages about this property in 2 different dependencies

Open PR in these projects.

> And since I can't override autoprefixer settings

You can write custom PostCSS plugin to remove unnecessary warnings from `result.warning`. But I suggest spending this type on fixing the problem in dependencies.

> I get that you want people to use the new property, but I don't think its time to already show deprecation messages on the color-adjust since that will remain working for a while.

It is not the first warning in Autoprefixer about deprecated syntax. https://github.com/postcss/autoprefixer/blob/main/lib/processor.js#L115-L326=

**Comment by vhscom** [comment]
Two wrongs don't make a right. This issue was opened 19 days ago and today there's a warning in my console. It's okay to nudge individuals to upgrade when things become unsupported but not deprecated.

**Comment by vhscom** [comment]
> I get that you want people to use the new property, but I don't think its time to already show deprecation messages on the `color-adjust` since that will remain working for a while.

Considering the property is deprecated in a W3C Recommendation suggests the change is already overdue.
