### ISSUE TITLE
Using standalone version

### ISSUE THREAD

**Issue by 3askaal** [postcss/autoprefixer#1521]
I have a question. Wanted to open a new ticket for it since other related tickets are really old.

I would love to use the standalone version of autoprefixer that works at runtime in the browser, is there any way to use it without copying the whole source from the rails package as mentioned in the readme (https://raw.githubusercontent.com/ai/autoprefixer-rails/master/vendor/autoprefixer.js). Would be nice to have the up-to-date version in a project.

**Comment by ai** [comment]
Just use bundler like Vite to build JS bundle with all Autoprefixer files. Autoprefixer is specially ready for that case. 

You need to have something like that in your app JS file (see JS API section of docs for what you need to do next): 

```js
import autoprefixer from 'autoprefixer`
```

I am closing the issue since we have this feature. But feel free to ask any additional questions here.

**Comment by 3askaal** [comment]
@ai thanks for answering, I found a quick solution that works for my case (working with objects only), I will need this later so thanks for the info.
