### ISSUE TITLE
-webkit-progress-{bar,value}, -moz-progress-bar

### ISSUE THREAD

**Issue by flying-sheep** [postcss/autoprefixer#180]
hi, autoprefixer misses that one.

there’s basically
1. `::-webkit-progress-bar`, which is the whole bar (so idk why it’s there since we can just style `progress`)
2. `-webkit-progress-value` and `-moz-progress-bar`, which are the progress indicator
3. `progress:indeterminate`, which means the same as `progress:not([value])`, but it’s not prefixed anyway.

**Comment by corysimmons** [comment]
Anyone happen to know if browsers finally standardized something for this? I can't find much.

If there is no standard, can we just make one and use it to serve the best solutions to various browsers? I know it'd feel dirty, but it seems like there is _some_ consensus between Chrome/FF with `::-webkit-progress-value`, `::-moz-progress-value`. /shrug

Anyone happen to know of a good lib that focuses on this rather than having to load all of WtfForms? :)

**Comment by ai** [comment]
@corysimmons without a standard we don’t know a unprefixed value, so we couldn’t use it in Autoprefixer :(

**Comment by corysimmons** [comment]
I feel ya. I might write some silly plugin that helps with this in a modular (just progress bars, or just xyz, instead of loading CSS for everything) if I get time (see: never). 🤔
