### ISSUE TITLE
3D transform functions should be stripped for IE9

### ISSUE THREAD

**Issue by garrettberg** [postcss/autoprefixer#210]
Per [Can I Use](http://caniuse.com/#search=transforms), IE9 supports transforms with the `-ms` prefix, but not 3D transforms. IE10 supports 3D transforms, but does not use the prefix. Can a "hack" be added to strip all 3D functions (`*Z()` and `*3d()`) for the `-ms` prefixed rule?

Input:

``` css
transform:translateX(10px) translateZ(0);
```

Output:

``` css
-webkit-transform:translateX(10px) translateZ(0);
-ms-transform:translateX(10px) translateZ(0); /* invalid and ignored in IE9 */
transform:translateX(10px) translateZ(0);
```

Expected Output:

``` css
-webkit-transform:translateX(10px) translateZ(0);
-ms-transform:translateX(10px);
transform:translateX(10px) translateZ(0);
```

**Comment by EasterPeanut** [comment]
As per now, if you have this input:

**Comment by EasterPeanut** [comment]
This is a great solution because translateZ will now be ignored in IE9. But when I try this as input (as fallback for IE9):
````
-ms-transform: translateX(10px);
transform: translateX(10px) translateZ(0);
````
I get this same output (-ms-transform property gets removed): 
````
-webkit-transform: translateX(10px) translateZ(0);
transform: translateX(10px) translateZ(0);
````

When I try this in the autoprefixer playground, I do get the expected output though; including the -ms-transform. In my project (Webpack project) I am using autoprefixer 6.7.7. Any idea on what could be causing this?

**Comment by ai** [comment]
@EasterPeanut 

1. Update your Autoprefixer. The latest version in 7.1.2.
2. Check that you have IE 9 in your target browsers. For example, default browsers doesn’t contain IE 9 anymore. Try http://browserl.ist/
