### ISSUE TITLE
Placeholder selector doesn’t work

### ISSUE THREAD

**Issue by pepelsbey** [postcss/autoprefixer#287]
When you specify `::placeholder` selector by the spec:

```
input::placeholder {
    color:red;
    }
```

…Autoprefixer is wisely converting it to following code:

```
input::-webkit-input-placeholder,
input::-moz-placeholder,
input:-ms-input-placeholder,
input::placeholder {
    color:red;
    }
```

But the problem is that above selector just doesn’t work when listed using commas. The only way to make it work is to put multiple declarations blocks, like this:

```
input::-webkit-input-placeholder {
    color:red;
    }
input::-moz-placeholder {
    color:red;
    }
input:-ms-input-placeholder {
    color:red;
    }
input::placeholder {
    color:red;
    }
```

Which is very sad, but true :(

**Comment by stevenvachon** [comment]
I had the same damn problem, but due to `cssnano`.

**Comment by ben-eb** [comment]
cssnano should not merge vendor prefixed rules together, if you have a reproducible bug then please open an issue.

https://github.com/ben-eb/postcss-merge-rules/blob/master/src/__tests__/index.js#L163-L169

**Comment by stevenvachon** [comment]
I just hadn't noticed them in the file because there were many characters between then and I was searching for `:placeholder` instead of `placeholder`. No bug, the mangled code works.

**Comment by gibbitz** [comment]
okay, it's been 3 years and I seem to be running into this. I'm using a SCSS placeholder to generate comma separated selectors and finding that autoprefixer isn't working for `::placeholder` in the output selector set. I'm working around the problem, but it's requiring me to add the code multiple times to the output css (via mixin). Did this bug fall off the radar or is there some other reason why `::placeholder` can't work like other selectors in groups? Is this just somethign that autoprefixer can't do that I haven't noticed (since it usually manipulates properties not selectors)?

**Comment by ai** [comment]
@gibbitz 

1. Check that your browserslist has browsers which need prefixes for `::placeholder`.
2. Check PostCSS alone, maybe some tool after PostCSS broke the code.
