### ISSUE TITLE
Producing sourcemaps with Compass and Autoprefixer returns runtime error

### ISSUE THREAD

**Issue by djmtype** [postcss/autoprefixer#370]
I added this to my `config.rb` file. 

```
require 'autoprefixer-rails'

on_stylesheet_saved do |file|
  css = File.read(file)
  map = file + '.map'

  if File.exists? map
    result = AutoprefixerRails.process(css,
      from: file,
      to:   file,
      map:  { prev: map, inline: false })
    File.open(file, 'w') { |io| io << result.css }
    File.open(map,  'w') { |io| io << result.map }
  else
    File.open(file, 'w') { |io| io << AutoprefixerRails.process(css) }
  end
end
```
This returns the error: 
```
ExecJS::RuntimeError on line ["47"] of /Users/me/.rvm/gems/ruby-2.1.0@global/gems/execjs-2.2.1/lib/execjs/ruby_racer_runtime.rb: SyntaxError: Unexpected token /
```

If I declare the following without source map detection, then everything outputs fine: 
```
require 'autoprefixer-rails'

on_stylesheet_saved do |file|
  css = File.read(file)
  File.open(file, 'w') do |io|
    io << AutoprefixerRails.process(css)
  end
end
```

Also, I am not using a task manager such as Gulp or Grunt, just Compass (1.01) which also installs Sass (3.4.9). I have autoprefixer-rails (4.0.2.2) installed.

**Comment by ai** [comment]
Yeap, I know about this issue, but has no idea how to fix it. It happens somewhere in ExecJS. Problem is that on [47 line](https://github.com/ai/autoprefixer-rails/blob/master/vendor/autoprefixer.js#L47).

If you know Ruby, I can suggest you to change ExecJS runtime (to node.js, for example).

But best case is to move to Gulp, because Gulp will open to you entire world of other awesome plugins (like other PostCSS plugins, or imagemin tool).
