### ISSUE TITLE
Inline source maps are not working

### ISSUE THREAD

**Issue by aexmachina** [postcss/autoprefixer#384]
I'm using broccoli-autoprefixer in an ember-cli project, and the source map is not working when autoprefixer is used. If I remove autoprefixer then the source maps work correctly.

- ember-cli-sass is correctly producing an inline source map `/*# sourceMappingURL=data:application/json;base64,...` 
- I'm setting `sourcemap: true` when I call broccoli-autoprefixer
- There is a `sourceMappingURL` included at the end of the CSS file, but it's broken: DevTools doesn't show the SCSS source, just the final output CSS

FWIW, I'd also like to add that I'd much prefer to be able to use a `.map` file, rather than having to embed the source map inline in the CSS file. The current beta of broccoli-sass (I'm a maintainer of broccoli-sass) uses `sourcesContent` to embed the source files into the source map, so this is quite a bit of data and I'd much prefer for the browser to be able to request the source map when it needs it, rather than it being force-fed inline in the CSS.

I can provide an example repo if this helps to debug the problem.

**Comment by ai** [comment]
Do you excuse me if I send you to `broccoli-autoprefixer` project? Please create a issue with example and post link here. I will support you in that issue to make `broccoli-autoprefixer` faster.

I think that problem is only in `broccoli-autoprefixer` because [PostCSS](https://github.com/postcss/postcss) (Autoprefiixer foundation) has the best source map support (with previous map updates). Gulp, Grunt and webpack users hasn’t problems.

**Comment by aexmachina** [comment]
No problem at all, wasn't sure whether to add it here or there.
