### ISSUE TITLE
Support "appearance"?

### ISSUE THREAD

**Issue by tobiastom** [postcss/autoprefixer#43]
I see that `appearance` is not supported equally through different browsers, but maybe at least some

    appearance: none
    -webkit-appearance: none
    -moz-appearance: none

support would be nice?

**Comment by jasonkuhrt** [comment]
@ai There appears to be data available now at Can I Use: http://caniuse.com/#feat=css-appearance

Since it is non-standard I think what we should do is let users enter this:

```
.foo { appearance: none; }
```

**Comment by jasonkuhrt** [comment]
Whoops, prematurely entered the comment above, make sure to re-read if you were reading in email client. Sorry!

**Comment by jasonkuhrt** [comment]
To be clear, I think if the data is available in Can I Use, we should support it. Peoplke ***will*** benefit from it, and if the sticking point is "non-standard" then we just need to correctly ***frame***/***communicate*** the feature; its an ***interface*** issue. Saying "nope, we're not going to support this" is dumb if the underlaying data is available and ***people are using this anyways***.

**Comment by ai** [comment]
@jasonkuhrt create a PostCSS plugin for this non-standard cases, like @yisibl 
`created [CSS Grace](https://github.com/cssdream/cssgrace) for IE hacks.

I want to add this property too. But I can’t do it. Becuase after few years there will be no prefixes. And right now Autoprefixer works in that case, that you will remove it after few years.

If your CSS will contains `appearance: none`, it will be broken without Authoprefixer.

Of course, we can add warnings and extra options. But right now Autoprefixer is the slowest PostCSS plugin because of many extra non-standard cases. Autoprefixer’s code base is complicated, so only I maintain it. Extra option for this non-standard cases make it more complicated. And we have no really reasons for this victims.

You can really write PostCSS plugin for `appearance` by few lines of code:

```js
module.exports = function (css) {
    css.eachDecl('appearance', function (decl) {
        if ( decl.value != 'none' ) return;
        decl.cloneBefore({ prop: '-webkit-appearance' });
        decl.cloneBefore({ prop: '-moz-appearance' });
        decl.removeSelf();
    });
};
```

Thats all! You need only `README.md` and tests. You can use [postcss-size](https://github.com/postcss/postcss-size) plugin a boilerplate.

**Comment by jasonkuhrt** [comment]
@ai Yeah that's all fair.

**Comment by ai** [comment]
Do you want to release and maintain `postcss-appearance` by snippet above?

**Comment by jasonkuhrt** [comment]
@ai Nope ; ) Which probably means its not important enough. If I change my mind I will let you know.

**Comment by ai** [comment]
@jasonkuhrt why not? it is about 30 minutes. Same time that you spend in this issue :).

**Comment by jasonkuhrt** [comment]
@ai Sort of, but it turns out we don't need this property anymore (right now). If the use-case comes back, maybe! : )

**Comment by yisibl** [comment]
CSS Grace maybe support its.

**Comment by ai** [comment]
@yisibl It will be nice.

**Comment by simevidas** [comment]
Update: https://github.com/postcss/autoprefixer-core/issues/14#issuecomment-93640159

**Comment by ai** [comment]
Becuase `appearance` with `auto` and `none` [became a standard](http://www.w3.org/blog/CSS/2015/04/15/minutes-telecon-244/) again, Autoprefixer 5.2 will have `appearance` support.

**Comment by ai** [comment]
Done https://github.com/postcss/autoprefixer-core/commit/dfc98f4cc873970518e897dfaf6e23771074d748
