### ISSUE TITLE
browser query "android >= 4.3" doesn't produce old flexbox syntax

### ISSUE THREAD

**Issue by fabyeah** [postcss/autoprefixer#432]
Query *android >= 4.2* will produce **display: -webkit-box;** but *android >= 4.3* won't, even though it's the last android version to use the old syntax.

Also, for old flexbox syntax, I would expect **flex-flow: row wrap;** to produce **flex-direction: row;** and **flex-wrap: wrap;**, but it doesn't. Why? I guess it's not technically 'prefixing'? But would be helpful.

**Comment by ai** [comment]
Sorry, I am preparing for my first English talk in Helsinki, so I will look at this issue only after April 15.

**Comment by ai** [comment]
@iamvdo found issue source. Can I Use stores data for Android 4.2 and 4.3 together. He fix Browserslist, but I can use new version only in next 5.2 release, which will be released in end of the April (sorry, English talk in Helsinki).

But you will not miss anything, if you will use `android >= 4.2` instead of `android >= 4.3`. So, I think this issue is minor.

**Comment by fabyeah** [comment]
Awesome. Thank you and thanks @iamvdo.

**Comment by iamvdo** [comment]
Yep. ;)
I found another bug.
Versions 4.4.3 and 4.4.4 of Android work as if they are 4.4 (because of parseFloat)

Very, VERY, minor bug.
