### ISSUE TITLE
Fatal error: unknown word

### ISSUE THREAD

**Issue by lerichard95** [postcss/autoprefixer#468]
I'm using this to auto prefix some CSS that I am using for a Tumblr theme, but the task fails when it encounters a Tumblr {CustomCSS} tag. I don't think postcss works for any Tumblr markup tags at all.

**Comment by ai** [comment]
Can you show bigger example?

**Comment by ai** [comment]
Right now PostCSS can’t parse `{` in CSS, because it is illegal construction.

But PostCSS 4.2 will have custom parsers, so you will be able to write correct parser for Tumblr: https://github.com/postcss/postcss/issues/140

Right now you can do some hack:

1. Replace `{` to `[`
2. Process by Autoprefixer
3. Replace `[` back to `{`.
