### ISSUE TITLE
Sourcemaps are breaking

### ISSUE THREAD

**Issue by bryanerayner** [postcss/autoprefixer#542]
I'm encountering an error with autoprefixer and sourcemaps.

````js

// sassStream is the output of gulp.src()
var autoprefixed = sassStream
            .pipe(sourcemaps.init({ loadMaps: true }))
            .pipe(postcss([autoprefixer()]))
            .pipe(sourcemaps.write('.', { includeContent: false}))
            .pipe(gulp.dest(destFolder));
````

I know this is gonna sound bad, but I don't even have an error message. It doesn't display properly in the console.

If this is an incorrect use case, then the ReadMe needs to be updated. How can this be corrected?

**Comment by ai** [comment]
Ask in gulp-postcss. Autoprefixer just small plugin for PostCSS ;-).

But I think, you should init source map before Sass. Most problems in source maps happen because of paths conflict. So, gulp-sass and gulp-postcss try to fix own paths based on Gulp base directory. Because you init source map after the Sass, it will not fix own paths.
