### ISSUE TITLE
Convert overflow-wrap into word-wrap

### ISSUE THREAD

**Issue by AurelioDeRosa** [postcss/autoprefixer#558]
Hi.

Would you consider adding the conversion of [`overflow-wrap`](http://caniuse.com/#feat=wordwrap) into `word-wrap` to improve compatibility with Firefox, Internet Explorer, and some older browsers?

**Comment by ai** [comment]
Autoprefixer works only with prefixes. If you want a polyfill, please write other PostCSS plugin.

**Comment by Schweinepriester** [comment]
I disagree, as autoprefixer handles e.g. `order: $val;`

Via <https://autoprefixer.github.io/>

```
order: $val;
```

Using e.g. `IE 10` as filter:

```
-ms-flex-order: $val;
order: $val;
```

While `-ms-flex-order: $val;` of course is prefixed with `-ms`, its actually a [different property (`flex-order`)](http://www.w3.org/TR/2012/WD-css3-flexbox-20120322/#flex-order) or at least an "alternate name", too.

And converting `overflow-wrap` into `word-wrap` isn't wanting a polyfill; browsers kinda just didn't rename `word-wrap` to `overflow-wrap`.

From <https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap>:

> Note: Originally a Microsoft (unprefixed) proprietary extension, the word-wrap property has been renamed overflow-wrap in the current draft of the CSS3 Text specification. word-wrap is now considered an "alternate name" for overflow-wrap. Stable builds of Google Chrome and Opera support the new syntax.

I don't think, though not tested, having both is causing an issue.

Browser support of the functionality is very deep: <http://caniuse.com/#feat=wordwrap>

I'd very much like to see the conversion implemented.

**Comment by ai** [comment]
The problem is that `overflow-wrap` has no prefix.

Why you can't write a PostCSS plugin and add it to cssnext plugin pack? We can help you in PostCSS gitter chat.

**Comment by Schweinepriester** [comment]
Ah, I see, it's kind of a technical issue, I thought it's something else.

Well, then of course a plugin would be appropriate.

**Comment by Schweinepriester** [comment]
For reference:

- <https://github.com/sivan/postcss-csssimple> seems to support adding `word-wrap`.
- <https://github.com/jonathantneal/postcss-time-machine> can at least replace `overflow-wrap`

**Comment by isiahmeadows** [comment]
Okay...this does sound prefixey enough IMHO to merit being added &ndash; it's an alias with exactly the same functionality, but different name. [1] There's also the alias `word-break`, an old WebKit alias with otherwise the exact same functionality.

It was originally an unprefixed non-standard extension by Microsoft back in IE 5, before prefixing properties was commonplace. There wasn't much standard to begin with, either. CSS3's overflow-wrap is merely a better-named alias of the old version.

[1] Prefixed declarations are treated identically to regular declarations in the CSS spec in every way except taking advantage of a reserved syntax. If `-moz-border-radius` conforms to the `border-radius` spec, then the only difference here is name. I see the same difference with `word-wrap`, `word-break`, and `overflow-wrap`.

**Comment by isiahmeadows** [comment]
@ai Could you consider opening this bug? This isn't asking for any polyfill here. I would also like to note that `overflow-wrap` and `word-wrap` are [specified to be equivalent by the relevant CSS3 spec](https://drafts.csswg.org/css-text-3/#overflow-wrap-property), with the former being the canonically preferred version.

**Comment by isiahmeadows** [comment]
Well...correction: I mis-interpreted `word-break`. CSS isn't my native language here. :smile:

My point still stands with `overflow-wrap` and `word-wrap`, with the former triggering the latter.

**Comment by ai** [comment]
@isiahmeadows why you think that `overflow-wrap` is a “prefix” for `word-wrap`? And why writing a other PostCSS plugin is not a solution here?

**Comment by isiahmeadows** [comment]
It's basically an alias, much like many of the vendor prefixes. The only
difference is that this is an alias mandated by spec instead of an
experimental implementation behind a prefix. I think it's this distinction
where you're saying it may not necessarily fall into the scope of
Autoprefixer. Am I correct in my understanding?

Although you're correct in that it could be written into another PostCSS
plugin pretty easily.

**Comment by ai** [comment]
Ping me, when you finish a plugin.

Also we have a support chat for plugin developers: https://gitter.im/postcss/postcss

**Comment by isiahmeadows** [comment]
@ai I don't have a huge investment in it (Stylus has transparent mixins), so I probably won't be too quick to write one. Sorry if I gave that impression.

**Comment by isiahmeadows** [comment]
This is more of a "nice to have", but I don't normally use PostCSS outside of this.
