### ISSUE TITLE
autoprefixer not prefixing calc()

### ISSUE THREAD

**Issue by acerspyro** [postcss/autoprefixer#575]
Old Webkit browsers require you to prefix calc() like -webkit-calc(), but using Autoprefixer via Grunt after building the Sass file does not appear to prefix it.

**Comment by ai** [comment]
1. https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius
2. http://caniuse.com/#feat=calc

`calc` do not need prefixes since `Safari 6` or `Chrome 25`. If you (by some strange reason) add them to `browsers` option, Autoprefixer will add this prefixes for `calc`.
