### ISSUE TITLE
Rename to postcss-autoprefixer

### ISSUE THREAD

**Issue by MoOx** [postcss/autoprefixer#597]
Now that autoprefixer is a pure PostCSS plugin, and now that PostCSS is famous enough and have a solid ecosystem (plugins, runners), maybe it's time to rename this plugin to follow the postcss-* convention.
(note: cssnext is going to be a pure coming in the next few days/weeks and will do the same (postcss-cssnext).

**Comment by ai** [comment]
Hmm. Yeap, I agree that `postcss-autoprefixer` is a better name. But we need next major release to do it.

So maybe we do it when PostCSS 6.0 release.

**Comment by MoOx** [comment]
Why do you want a major bump of postcss itself to make this change?

**Comment by ai** [comment]
Project name is a public API

**Comment by MoOx** [comment]
You can deprecate autoprefixer on npm, people can still use it (not breaking changes, just a warning during npm install) + rename to postcss-autoprefixer without any breaking change in the API.
What am I missing?

**Comment by ai** [comment]
Yeap, we can keep `autoprefixer` package with link to `postcss-autoprefixer`. But anyway people will need to update their `package.json` and I prefer to make this changes in major releases.

**Comment by yisibl** [comment]
I don't recommend changing the name. From the beginning of the `autoprefixer-core` to `autoprefixer`. We have changed two times. For developers, this will be very confusing.

**Comment by MoOx** [comment]
autoprefixer is a postcss plugin. In order to provide some consistency in the postcss ecosystem, I think this is a requirement that this plugin name contains the prefix `postcss-`.
Babel ecosystem is doing the same (all plugin prefixed) and it works great. Don't be afraid of a change like this: npm provides a way to notify downloaders of change like this via `npm deprecate`.

**Comment by ai** [comment]
@MoOx yeap, I think to rename project. I just want to wait next big release.

**Comment by ghostropic** [comment]
When using autoprefixer through postcss through gulp, should I be using `npm install autoprefixer` or  `npm install gulp-autoprefixer`?  The reason I asked is because neither are working for me.   `npm install autoprefixer`gives a number of errors relating to `inotify.h` and `npm install gulp-autoprefixer` installs successfully but when I run gulp it does nothing. If I don't get to the bottom of it soon I'll  either open an issue about the `inotify.h` error or post something on stack but before I can get to the root of the issue I need to find on which stem to pull on.

**Comment by ai** [comment]
@ghostropic we have a special section about Gulp and it do not tell anything about `gulp-autoprefixer`. You should use `gulp-postcss` with `autoprefixer`

https://github.com/postcss/autoprefixer#gulp
