### ISSUE TITLE
Possible to run without accessing caniuse data?

### ISSUE THREAD

**Issue by benfrain** [postcss/autoprefixer#658]
I'm wondering if it is possible to config Autoprefixer so that it doesn't need to access caniuse data? For example, if my config is explicit e.g.:

{ browsers: [“ie > 8”, “safari >= 6”] }

Does this still make a call to caniuse data? We recently had an issue where flex based prefixes were omitted in our builds because a fresh `npm install` was bringing down autoprefixer with later caniuse data. This was in turn removing some prefixes we still needed.

It would be advantageous for us to NOT reference caniuse data as a safeguard and just prefix based upon explicit browsers listed in our config. Is this a possibility? 

Sorry if I am misunderstanding the way Autoprefixer goes about its magic :)

**Comment by ai** [comment]
Short answer: no :). But full answer will be not so sad for you :).

We can’t omit `caniuse-db`, because we use it not only for browsers versions. We [take](https://github.com/postcss/autoprefixer/blob/master/data/prefixes.coffee#L61) all prefixes data from `caniuse-db`.

But, because `caniuse-db` is just a npm package, I know how to fix you pain in better way :). Also we use it every day in production, so I am sure in it. Just lock `caniuse-db` version in `package.json`:

```
"dependencies": {
    "autoprefixer": "6.3.6",
    "caniuse-db":  "1.0.30000466"
}
```

npm works recursively, if it found library in upper level (for example in `project/node_modules`) it will not install other version into sub-dependencies (for example, to `project/node_modules/autoprefixer/node_modules`). This is why you can lock Autoprefixer’s `caniuse-db` version in your project’s `package.json`. It works with npm@2 and @npm@3.

**Comment by ai** [comment]
But maybe `npm-shrinkwrap.json` is better solution. It will lock all npm dependencies, so `caniuse-db` version will be locked too.

**Comment by benfrain** [comment]
Thanks Andrey, massive help as usual 👍

**Comment by benfrain** [comment]
Hi Andrey, not sure what I am doing wrong. Is it necessary to lock both autoprefixer and caniuse-db? I ask because:

I have a test CSS rule:

.aa { display: flex; }

And the required output is:

.aa {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}


With this as my package.json for Autoprefixer:

"autoprefixer": "^6.3.3”,

After a clean install of NPM, the caniuse in Autoprefixer is:

"version": "1.0.30000466"

Running the test yields (missing necessary prefixes):

.aa {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}

If I then add this to my project root package.json dependencies (to set a specific data set of known 'good' caniuse data):

"caniuse-db": “1.0.30000415”

Delete node_modules and re-run npm install

Re-running the test I still get:

.aa {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}

**Comment by ai** [comment]
What browsers config do you have?

**Comment by benfrain** [comment]
*Slaps big fat bald head*!

**Comment by benfrain** [comment]
👍
