### ISSUE TITLE
compiles transition property name with webkit prefix

### ISSUE THREAD

**Issue by kamlekar** [postcss/autoprefixer#716]
## Input

    .rotate:hover{
          transition-name: opacity, transform;
          transition-duration: 10s, 1s;
    }

## Compiled output

    .rotate:hover {
         -webkit-transition-property: opacity, -webkit-transform;  /* WRONG */
                 transition-property: opacity, -webkit-transform;  /* WRONG */
                 transition-property: opacity, transform;         /* CORRECT */
                 transition-property: opacity, transform, -webkit-transform;    /* WRONG */
         -webkit-transition-duration: 10s, 1s;
                 transition-duration: 10s, 1s;
    }

Autoprefixer is rendering the inside transition duration names with vendor prefixes which is breaking the animation because chrome is giving priority to `-webkit-transition-duration` instead of `transition-duration`.

[**Fiddle**](http://codepen.io/anon/pen/bwZdrV)

## Expected output:

    .rotate:hover {
         -webkit-transition-property: opacity, transform;  
                 transition-property: opacity, transform;         /* CORRECT */
         -webkit-transition-duration: 10s, 1s;
                 transition-duration: 10s, 1s;
    }

**Comment by ai** [comment]
Use `transition` instead of `transition-property` and `transition-duration`.

I know that it is not ideal, but there is not 100% correct way to prefix transitions for all browsers (we discuss about it a lot and didn’t find solution). Your expected output will not work, because some browser of your select requires `-webkit-transform`.
