### ISSUE TITLE
npm install fails: ERR! cb() never called!

### ISSUE THREAD

**Issue by alessandrocm** [postcss/autoprefixer#761]
Cannot install npm package.

> npm i autoprefixer
 npm ERR! cb() never called!

node: v5.9.1
npm: 4.0.3

**Comment by ai** [comment]
Please update `node`. Your `node 5 doesn’t supported by Node Foundation anymore. They don’t even publish a security updates, so using node 5 is very dangerous to your company.

This issue happens because `caniuse-db` is not supported in node 5. Nobody will fix it because node 5 is dangerous and should not be used by anyone.

More details: https://github.com/Fyrd/caniuse/issues/2981

**Comment by ai** [comment]
Also, please follow our Twitter, we announced about this issue (and node 5 problems) few months before https://twitter.com/autoprefixer
