### ISSUE TITLE
transition-property wrongly prefixed

### ISSUE THREAD

**Issue by wearetelescopic** [postcss/autoprefixer#774]
This:

`transition-property: bottom, transform;`

becomes:

```
-webkit-transition-property: bottom, -webkit-transform;
  transition-property: bottom, -webkit-transform;
  transition-property: bottom, transform;
  transition-property: bottom, transform, -webkit-transform;
```
which doesn't work, it should be:

```
-webkit-transition-property: bottom, -webkit-transform;
transition-property: bottom, transform;
```

**Comment by ai** [comment]
It could not be be `-webkit-transition-property: bottom, -webkit-transform;` because there are browsers, which support `transition`, but require `-webkit-transform`.

Autoprefixer show a warning (if you use recommended Gulp/webpack/CLI, instead of text editor plugins) that you should use `transition` instead of `transition-property`, because there is no way to prefix `transition-property` correctly.

**Comment by wearetelescopic** [comment]
Ah yes, switched to transition only then, ta!
