### ISSUE TITLE
Check -webkit-background-clip again

### ISSUE THREAD

**Issue by ai** [postcss/autoprefixer#831]
https://drafts.csswg.org/css-backgrounds-4/#valdef-background-clip-text

**Comment by AmeliaBR** [comment]
Some comments:

- right now, all browsers that support `background-clip: text` (aka, Firefox and Edge) also support `-webkit-background-clip: text`
- other browsers (Blink and WebKit) only support the `-webkit-` version
- there are no other prefixes that I know of that include the `text` value
- it is usually used in combination with `-webkit-text-fill-color` in order to coordinate styles to only apply in browsers that support.  There is not yet support for an unprefixed version of this property, although [a standard `fill-color` is proposed](https://drafts.fxtf.org/fill-stroke-3/#fill-color).

But prefixes are ugly, and a dev working on Firefox or Edge as their main browser currently needs to remember to add in the prefixes for Chrome & Safari etc.

___________________

Possibly relevant usage stats from Microsoft's analytics:

- [`-webkit-background-clip: text`](https://developer.microsoft.com/en-us/microsoft-edge/platform/usage/css/-webkit-background-clip/) is served to Chrome by approximately 0.03% of pages (763/2,354,088)
- [`background-clip: text`](https://developer.microsoft.com/en-us/microsoft-edge/platform/usage/css/background-clip/) is computed by Firefox / Edge (meaning they get served it either prefixed or un-prefixed: they treat the prefix as a shorthand for the unprefixed, and the MS data doesn't record shorthands, only computed values) on approximately 0.02% of pages (429 or 488 /2,354,088)

Which tells me that the number of sites using browser sniffing or CSS selector hacks to avoid sending `-webkit-` properties to Firefox and Edge is greater than the number of sites using `background-clip: text` without prefixes.

**Comment by ai** [comment]
Closing since nobody added data to Can I Use

**Comment by sombreroEnPuntas** [comment]
Is this closed because it was fixed?  
`caniuse` says to use the prefix: https://caniuse.com/#search=background-clip

I am not getting it, and have to manually add it :o

**Comment by ai** [comment]
@sombreroEnPuntas it was closed because no one decided to add prefix data to Can I Use. So seems like it is not necessary. 

Right now Can I Use show prefix only in comments. But we need to show it in versions blocks. If you want t have this feature in Autoprefixer, maybe you can create a separated `css-blackground-clip` data for Can I Use.

**Comment by sombreroEnPuntas** [comment]
I see. I actually tried to understand the format on their repo, but don't get it :s  
Not sure how to move the prefix from the comments to version blocks

**Comment by ai** [comment]
@sombreroEnPuntas 

1. You need to create new file in `features-json/`
2. Here is fields description https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md

**Comment by ai** [comment]
Done 73c7b6a

**Comment by ai** [comment]
Released in 9.1

**Comment by sombreroEnPuntas** [comment]
Awesome!

Out of curiosity... can you point me to the commit on `caniuse` that added the prefixing options?

**Comment by ai** [comment]
It is closed because it was fixed in the `master`. I will release the fix in next `caniuse-db` release.
