### ISSUE TITLE
Old prefixes have returned

### ISSUE THREAD

**Issue by philwareham** [postcss/autoprefixer#832]
Hi there,

Just updated to Autoprefixer 7.0.1 alongside PostCSS 6.0.1, I have the following in my `package.json` file...

    "browserslist": [
      "last 3 versions",
      "not ie <= 11"
    ]

...and I seem to be getting old `-o-`, `-moz-` and `-webkit-` rules reintroduced into my processed CSS file which were not present when using Autoprefixer 6.x (and I'm pretty sure are not part of the last 3 browser versions of those browsers).

Tried using the config within my `Gruntfile.js`, `package.json` and a `.browserslistrc` file but same results each way. Anyone else getting this behaviour?

**Comment by ai** [comment]
In Browserslist 2 we changed `last n versions` logic. Now it includes last `n` versions for all browsers, not just major.

You can read the reasons in ChangeLog:
https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released

Don't worry about this extra prefixes, size will be the same because of gzip. You can find link to our discussion with Google engineer about it in ChangeLog.

**Comment by philwareham** [comment]
Ah, OK sorry, I didn't read that far down in the Browserlist 2 release notes :)

Makes sense now.
