### ISSUE TITLE
I guess something has changed after upgrading from 6 to 7

### ISSUE THREAD

**Issue by jitendravyas** [postcss/autoprefixer#842]
I'm getting different output after upgrade 
<img width="1349" alt="monosnap 2017-05-17 18-04-19" src="https://cloud.githubusercontent.com/assets/77309/26154043/8eef9254-3b2b-11e7-8eaf-42787520485b.png">

the content of my `browserslist` file

```
last 3 versions
not IE > 0
not ExplorerMobile > 0
not iOS > 0
```

**Comment by lydell** [comment]
The [7.0.0 changelog](https://github.com/postcss/autoprefixer/blob/77472b67ed16f93d3c523e5346409bf27d6c3859/CHANGELOG.md#70-coelestem-adspicit-lucem) says "Use Browserslist 2" and the [Browserslist 2.0.0 changelog](https://github.com/ai/browserslist/blob/f798a281c4ef17d8598de571e02faafb3f3db331/CHANGELOG.md#20) says "`last n versions` returns versions for all browsers, not only main browsers." That's why you're getting more prefixes – your browserslist now matches more browsers than it did before.

**Comment by jitendravyas** [comment]
Do I need to install browserlist too?

**Comment by lydell** [comment]
You don't need to do anything at all. Everything's fine.

**Comment by ai** [comment]
Yeap, Browserslist 2 changed `last n versions` behaviour. It is better, don’t worry.

**Comment by ai** [comment]
Prefixes was removed because of fresh Can I Use data, not because Browserslist 2.

**Comment by jitendravyas** [comment]
In my case prefix were added after upgrade not removed. I'm still not very clear though why those were added.

**Comment by ai** [comment]
@jitendravyas because `last n versions` now include all browsers (including Chinese browsers). They need more `-webkit-` prefixes.
