### ISSUE TITLE
Autoprefixer for Dreamweaver? 

### ISSUE THREAD

**Issue by mashablair** [postcss/autoprefixer#876]
Just checking if Autoprefixer will become available for Dreamweaver anytime soon?

**Comment by ai** [comment]
I am not sure that Dreamweaver has active development. Anyway, I am not sure, it is better to ask Dreamweaver team, they know better.

Also note, that we [don’t recommend](https://github.com/postcss/autoprefixer#text-editors-and-ide) to use text editor plugins since prefixes reduce readability. It is much better to start to use build tools (like Gulp). I know it is complicated at the beginning, but they the whole new world of CSS tools will be open for you.

**Comment by energylevels** [comment]
As Dreamweaver uses an embedded version of Brackets as its code editor, you would think it might be possible to port the Brackets Autoprefixer extension to Dreamweaver.
