### ISSUE TITLE
Safari and duplicate property display

### ISSUE THREAD

**Issue by richgcook** [postcss/autoprefixer#878]
I've found a few issues about this here but it doesn't ever seem to be resolved...

I'm using postcss/autoprefixer and have the browserlists list set up as a .browserslistrc file and that's all working well but when it comes to Safari and using flexbox I'm still getting this issue...

<img width="473" alt="screen shot 2017-08-18 at 17 11 32" src="https://user-images.githubusercontent.com/901289/29467402-5409e4ae-8438-11e7-8887-92bcd828219c.png">

Safari then completely ignores flexbox. I have the browserslist query set as `Last 2 versions`

Any thoughts?

**Comment by ai** [comment]
Current Safari doesn’t need `-webkit-` prefix and works with unprefixed version
http://caniuse.com/#feat=flexbox

`-webkit-` prefixes need for Chinese browsers with old webkit engine.

Maybe you have a problem in Safari because of `-webkit-box-orient` vs `flex-flow` conflict. Try to disable old flexbox for Chinese browsers by `flexbox` option https://github.com/postcss/autoprefixer#options

**Comment by richgcook** [comment]
I'm not using a Chinese browser? I'm based in the UK.

**Comment by ai** [comment]
`last 2 versions`in your browserslist means “last 2 versions of every browser on Earth”, so Autoprefixer generates prefixes for last 2 version of all exists browsers. This is a reason why you have `-webkit-` prefix for Safari (it doesn’t need this prefix for a year).

Here is a good webpage to debug browserslist queries: http://browserl.ist/?q=last+2+versions

**Comment by richgcook** [comment]
Ah okay so perhaps there is a browser in there that needs the -webkit- prefix? I tried using the "no-2009" option but it still adds one for IE which then creates an issue for Safari. Unsure why Safari is having such a hard time understanding cascading...

<img width="303" alt="screen shot 2017-08-19 at 15 10 33" src="https://user-images.githubusercontent.com/901289/29487431-ae664f88-84f0-11e7-8ad8-47b9123ac144.png">

**Comment by ai** [comment]
What issue for Safari you are talking about? CSS looks good. Safari ignores seeing prefixes and use unprefixed version.

**Comment by richgcook** [comment]
See the little warning icon next to 'display: flex'? It then doesn't run the display attributes and I'm left with no display attributes working. It seems like Safari isn't allowing two or more 'display' attributes (unlike other browsers that just ignore it... Safari seems to block it altogether).

**Comment by ai** [comment]
@richgcook can you show tooltip text when you will hover this warning icon?

It is very strange, that only you found that Autoprefixer output is broken for Safari and all other websites just doesn't work in Safari 😉

**Comment by richgcook** [comment]
<img width="296" alt="screen shot 2017-08-22 at 09 35 28" src="https://user-images.githubusercontent.com/901289/29556294-4d0f5d22-871d-11e7-97ef-f97610679ede.png">

I know what you're saying but I'm not doing anything else complex that would throw it off... just using a simple `display:flex` attribute.

**Comment by ai** [comment]
It is just warning, not error

**Comment by richgcook** [comment]
I totally understand but by doing so it's not using any of the display properties... it's ignoring them all.

**Comment by ai** [comment]
Why do you think it ignore them?

**Comment by richgcook** [comment]
Ah I dunno, man. Maybe I'm confusing things. Thanks for all your help.

**Comment by sebszocinski** [comment]
This issue is happening for me as well @richgcook you're not alone... stupid Safari... the new Internet Explorer.

**Comment by DanielEytan** [comment]
Same Issue here. Did you found a solution @richgcook?

**Comment by umesh-velir** [comment]
I was having the same issue on Safari 9 and 10 with nested display: flex, the children items were messed up. Since there is no way to change or define the order of css property in autoprefixer, I had to add display: -webkit-box right after display: flex in the css and that resolved the issue. Worked fine on latest Chrome and Safari 11 who don't need vendor prefix.

Example: 
HTML: 
`<div class="flex-parent">
  <div class="flex-child">
    <div class="flex-grandchild">grandchild 1</div>
    <div class="flex-grandchild">grandchild 2</div>
</div>
  <div class="flex-child">child2</div>
</div>`

CSS:
`.flex-parent {
  display: flex;
}
.flex-child {
  display: flex;
}
`
CSS Output with autoprefixer:
`.flex-parent {
  display: -webkit-box;
  display: flex;
}
.flex-child {
  display: -webkit-box;
  display: flex;
}
`
SOLUTION:
`.flex-parent {
  display: flex;
}
.flex-child {
  display: flex;
  display: -webkit-box; // just overriding the display order.
}`

Hope this helps you guys too. @DanielEytan, @richgcook, @sebszocinski

**Comment by PriyaNayak89** [comment]
Any solution for this issue ?

**Comment by ai** [comment]
@PriyaNayak89 what exactly issue do you have?

**Comment by Aaronfischer** [comment]
I'm seeing this issue as well (basically the same screenshot as https://github.com/postcss/autoprefixer/issues/878#issuecomment-323958547)

Essentially, safari isn't reading display:flex, or its conflicting with display:flex and the preceding display:-webkit-box.

If I "uncheck" display:flex, it works...

(Safari 9.1.X)

**Comment by ai** [comment]
Check other CSS, that you never have manually prefixes
