### ISSUE TITLE
php support

### ISSUE THREAD

**Issue by commonpike** [postcss/autoprefixer#944]
You wrote here
https://css-tricks.com/autoprefixer/

> If your environment doesn’t support Autoprefixer yet, please, report it and I’ll try to help.

and nobody wrote it yet ;-) so there you are.

**Comment by ai** [comment]
For this 2+ years of Autoprefixer nobody converted Autoprefixer to PHP, Ruby, Python or any other languages.

This is why I think nobody will wow it on PHP.

But there is a better way. Just use many systems to call Node.js from PHP. There are many solutions for it, but I can't recommend the best way for your case since I am not PHP developer anymore.

**Comment by ai** [comment]
For example, you can use this package: https://github.com/vladkens/autoprefixer-php

**Comment by commonpike** [comment]
That has a dependency Node.js, too. 

If that is impossible, as in my case, you can revert to autoprefixing mixins like https://github.com/JoelSutherland/LESS-Prefixer

**Comment by ai** [comment]
By the way, why you can't use Node.js?

**Comment by ai** [comment]
Less so a JS tool too, it can't be run on PHP only runtime

**Comment by commonpike** [comment]
I can't be sure the clients have Node.js installed, and I don't want to require it just for this. I am running a PHP LESS parser, fyi. There are several.

**Comment by TrySound** [comment]
@commonpike autoprefixer, less and others are predeploy tools. They should not be used directly on website user calls. It's like compilation step. It does not make sense to have ports in many languages since it's not runtime feature like for example [nanoid](https://github.com/ai/nanoid) which has ports in php btw.

**Comment by ai** [comment]
@commonpike what clients? You have some PHP engine and you give it to your clients, be so they could install it on their servers? And this engine had build-in CSS? Tell us about your product?
