### ISSUE TITLE
break-inside for modern firefox

### ISSUE THREAD

**Issue by shrpne** [postcss/autoprefixer#972]
`break-inside` not prefixed with `page-break-inside` for `last 2 Firefox versions` or `Firefox >= 52` configs
For `Firefox 51` config `page-break-inside` adds correctly.

`break-inside` not supported in any version of Firefox 
https://developer.mozilla.org/ru/docs/Web/CSS/break-inside

**Comment by ai** [comment]
It happened because Can I Use data changed.

I really think to remove `page-break-inside` from Autoprefixer since it never was a vendor prefix, just a hack/polyfill.

Maybe you should write custom PostCSS plugin. It is really easy. I think it will be just 10 LOC Anand I will help you with it. What do you think?

**Comment by shrpne** [comment]
Removing it will break backward compatibility for Firefox users.
`page-break-inside` is not a prefix, but an alias for `break-inside`, so I think it's fine to handle it with Autoprefixer

Honestly, I think Autoprefixer should allow writing **modern** CSS syntax without bothering of old/unsupported browsers and without adding other PostCSS plugins like cssnext, cssnext should be about **future** CSS syntax. That's why I did not like moving `overflow-wrap\word-wrap` to cssnext from Autoprefixer. But it is just my opinion :)

**Comment by ai** [comment]
> Removing it will break backward compatibility for Firefox users.

Yeap. I can do it only in major version :(.

> Honestly, I think Autoprefixer should allow writing modern CSS syntax without bothering of old/unsupported browsers

Autoprefixer is “not a polyfill” by design and by name ;).

> page-break-inside is not a prefix, but an alias for break-inside, so I think it's fine to handle it with Autoprefixer

I got opposite advice about `break-inside`. Somebody told me that `break-inside` != `page-break-inside`. Can you make some research? Maybe I will change my opinion about this property.

**Comment by shrpne** [comment]
`break-` properties is like 3-in-1 for `page-break-`, `column-break-` and `region-break-` 
(meanwhile `column-break-` exists only as `-webkit-column-break-` and `region-break` is not existent)

So when you write `break-inside: avoid` it should work as combination of `page-break-inside: avoid` + `column-break-inside: avoid` + `region-break-inside: avoid`

But with `break-` you can specify what type of break do you want: 
`break-inside: avoid-column` should work as `column-break-inside: avoid`

Also, old separated properties don't have values to force break, they only have `avoid` value and `auto` (neither forced nor forbidden)
So when you write `break-inside: page` or `break-inside: always` it has no equivalent in the old syntax.

**Comment by ai** [comment]
After many hours of thinking I decided to remove `break-*` → `page-break-*` for Firefox since it is not a prefix e1853af

I know that you love this feature, so I am sorry. But consistency is very important.

Also, there is a good project of “writing future CSS today”. It is [postcss-preset-env](https://github.com/jonathantneal/postcss-preset-env). Just ask them to add  `break-*` support. It will be much better place for polyfills and same things.

**Comment by shrpne** [comment]
postcss-preset-env is exactly what i need, can you please add it to the "Does it add polyfills?" readme section?

**Comment by ai** [comment]
Sure https://github.com/postcss/autoprefixer/commit/d44d9bd9888e037102394183f5799779b162b2af
