### ISSUE TITLE
IE11 grid-template-columns and grid-template-rows should prefix with -ms-grid-columns and -ms-grid-rows 

### ISSUE THREAD

**Issue by leocaseiro** [postcss/autoprefixer#984]
Hi, I tried to find some fixes for IE11 in regards to grid usage and I realised that the `grid-template-columns` and `grid-template-rows` should being prefixed as `-ms-grid-columns` and `-ms-grid-rows`.

Anyone else with the same issue? Should I send a PR?

**Comment by ai** [comment]
We already prefixing this properties. Did you set `grid: true` option?

**Comment by ai** [comment]
How did you use Autoprefixer? Gulp/grunt/text editor? Show your configs.

**Comment by developer3-distributed** [comment]
I just typed in text editor. I configured nothing for that.

**Comment by ai** [comment]
@developer3-distributed most of Autoprefixer plugins for text editor doesn’t support Grid. Use `gulp-postcss` with `autoprefixer`. Then set `require(''autoprefixer')({ grid: true })` in `postcss.config.js`.

**Comment by developer3-distributed** [comment]
ok, thank you. let me try

**Comment by Dan503** [comment]
Make sure to read all articles in this series before using CSS Grid. There are many limitations that you need to be aware of.

https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/

In Part 2 it references a guide on how to set up a project to use Autoprefixer.

If you aren't sure how to apply the setting then you can add an `/* autoprefixer grid: on */` control comment to your CSS file instead.

Autoprefixer now also has limited support for autoplacement as well now. Instead of using `{ grid: true }` in the settings, it is better to use `{ grid: "autoplace" }` or an `/* autoprefixer grid: autoplace */` control comment now.

Make sure to read the Autoprefixer [documentation on autoplacement](https://github.com/postcss/autoprefixer/blob/master/README.md#grid-autoplacement-support-in-ie) before attempting to use this feature though.
